---
- name: PHP FPM configuration
  template: dest=/etc/php-fpm.conf group=root mode=0644 owner=root src=php-fpm.conf.j2
  tags: fpm

- name: PHP FPM pools configuration
  template: dest=/etc/php-fpm.d/{{item.name}}.conf group=root mode=0644 owner=root src=pool.conf.j2
  with_items:  "{{ php_fpm_pools }}"
  tags: fpm
  notify: PHP-FPM