---
# tasks file for nudorm.php
- include: setup-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml

- name: Install PHP packages
  package: name={{ item }} state=present
  with_items: "{{ php_packages }}"
  tags: php

- name: Install php.ini file
  template: dest=/etc/php.ini group=root mode=0644  owner=root src=php.ini.j2
  tags: php

- name: Install FPM module
  package: name={{ php_fpm_package }} state=present
  when: install_php_fpm
  tags: fpm

- include: config-fpm.yml